"use client";

import { useState } from "react";
import {
  X,
  DollarSign,
  Users,
  Gift,
  Star,
  Crown,
  Zap,
  ChevronRight,
} from "lucide-react";
import { Card, CardContent } from "../ui/card";
import Image from "next/image";

interface AllBenefitsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const keyData = {
  steel: {
    name: "Steel Key Member",
    price: "$450 USDC",
    supply: "62 keys",
    color: "from-gray-600 to-gray-700",
    textColor: "text-gray-300",
    icon: "Steel.gif",
    benefits: [
      "Lifetime DRVN Culture premium membership & Presale access to every tokenized vehicle release",
      "0.1 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 500K $BSTR airdrop + Recurring $BSTR rewards",
      "A chance to win 1 full car share every time a vehicle is added to our collection",
      "DRVN Founder's Club phygital* hat",
      "DRVN PFP Airdrop – Uncommon (coming soon)",
    ],
  },
  carbon: {
    name: "Carbon Key Member",
    price: "$1,100 USDC",
    supply: "24 keys",
    color: "from-green-600 to-green-700",
    textColor: "text-green-300",
    icon: "Carbon.gif",
    benefits: [
      "All Steel level benefits, plus…",
      "0.25 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 1.25M $BSTR airdrop + Recurring $BSTR rewards",
      "VIP Presale access to every tokenized vehicle release",
      "DRVN Founder's Club phygital* jacket",
      "DRVN PFP Airdrop – Rare (coming soon)",
    ],
  },
  titanium: {
    name: "Titanium Key Member",
    price: "$4,000 USDC",
    supply: "7 keys",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-300",
    icon: "Titanium.gif",
    benefits: [
      "All Carbon level benefits, plus…",
      "1 full $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 4.75M $BSTR airdrop + Recurring $BSTR rewards",
      "Profit share on all revenue generated by the $RS1 Ferrari",
      "Exclusive $RS1 Ferrari phygital* merch",
      "Custom Key to the Ferrari",
      "Custom Titanium Club watch",
      "Titanium Club jacket",
      "DRVN PFP Airdrop – Legendary (coming soon)",
    ],
  },
};

export function AllBenefitsModal({ isOpen, onClose }: AllBenefitsModalProps) {
  const [selectedKey, setSelectedKey] = useState<
    "steel" | "carbon" | "titanium"
  >("steel");

  if (!isOpen) return null;

  const selectedData = keyData[selectedKey];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal Content */}
      <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <Card className="bg-gradient-to-br from-gray-900 to-black border border-gray-700 backdrop-blur-sm">
          <CardContent className="p-0">
            {/* Header */}
            <div className="p-6 border-b border-gray-700">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <Gift className="w-8 h-8 text-yellow-500" />
                  <h2 className="text-3xl font-bold text-white font-mono">
                    DRVN Key Benefits
                  </h2>
                </div>
                <button
                  onClick={onClose}
                  className="p-2 hover:bg-gray-800 rounded-full transition-colors"
                >
                  <X className="w-6 h-6 text-gray-400" />
                </button>
              </div>

              {/* Key Selection Tabs */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {Object.entries(keyData).map(([key, data]) => (
                  <button
                    key={key}
                    onClick={() =>
                      setSelectedKey(key as "steel" | "carbon" | "titanium")
                    }
                    className={`p-4 rounded-lg border transition-all ${
                      selectedKey === key
                        ? "border-yellow-500 bg-yellow-500/10"
                        : "border-gray-700 hover:border-gray-600"
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-12 h-12 rounded-xl overflow-hidden bg-gradient-to-r ${data.color}`}
                      >
                        <Image
                          src={`/Cars/${data.icon}`}
                          alt={`${data.name} Key`}
                          width={48}
                          height={48}
                          className="w-full h-full object-cover"
                          unoptimized
                        />
                      </div>
                      <div className="text-left">
                        <div className="text-white font-mono font-bold text-sm">
                          {data.name}
                        </div>
                        <div className="text-green-400 font-mono text-xs">
                          {data.price}
                        </div>
                      </div>
                      <ChevronRight className="w-4 h-4 text-gray-400 ml-auto" />
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Selected Key Details */}
            <div className="p-6">
              <div className="flex items-center gap-4 mb-6">
                <div
                  className={`w-20 h-20 rounded-xl overflow-hidden bg-gradient-to-r ${selectedData.color}`}
                >
                  <Image
                    src={`/Cars/${selectedData.icon}`}
                    alt={`${selectedData.name} Key`}
                    width={80}
                    height={80}
                    className="w-full h-full object-cover"
                    unoptimized
                  />
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white font-mono">
                    {selectedData.name}
                  </h3>
                  <div className="flex items-center gap-6 mt-2">
                    <div className="flex items-center gap-2">
                      <DollarSign className="w-5 h-5 text-green-400" />
                      <span className="text-green-400 font-mono font-bold text-lg">
                        {selectedData.price}
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Users className="w-5 h-5 text-blue-400" />
                      <span className="text-blue-400 font-mono text-lg">
                        {selectedData.supply}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Benefits List */}
              <div className="space-y-4">
                <h4 className="text-xl font-bold text-white font-mono mb-4 flex items-center gap-2">
                  <Star className="w-6 h-6 text-yellow-500" />
                  Member Benefits
                </h4>

                {selectedData.benefits.map((benefit, index) => (
                  <div
                    key={index}
                    className="flex items-start gap-4 p-4 bg-gray-800/50 rounded-lg border border-gray-700"
                  >
                    <div className="flex-shrink-0 mt-1">
                      {index === 0 && selectedKey !== "steel" ? (
                        <Crown className="w-6 h-6 text-yellow-500" />
                      ) : (
                        <Star className="w-6 h-6 text-yellow-500" />
                      )}
                    </div>
                    <p className="text-gray-300 font-mono text-sm leading-relaxed">
                      {benefit}
                    </p>
                  </div>
                ))}
              </div>

              {/* Footer */}
              <div className="mt-8 pt-6 border-t border-gray-700">
                <div className="flex items-center justify-center gap-2 text-sm text-gray-400 font-mono">
                  <Zap className="w-4 h-4" />
                  <span>
                    Limited Supply • Exclusive Access • Premium Benefits
                  </span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
