"use client";

import { X, DollarSign, Users, Gift, Star, Crown, Zap } from "lucide-react";
import { Card, CardContent } from "../ui/card";
import Image from "next/image";

interface BenefitsModalProps {
  isOpen: boolean;
  onClose: () => void;
  keyType: "steel" | "carbon" | "titanium";
}

const keyData = {
  steel: {
    name: "Steel Key Member",
    price: "$450 USDC",
    supply: "62 keys",
    color: "from-gray-600 to-gray-700",
    textColor: "text-gray-300",
    icon: "Steel.gif",
    benefits: [
      "Lifetime DRVN Culture premium membership & Presale access to every tokenized vehicle release",
      "0.1 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 500K $BSTR airdrop + Recurring $BSTR rewards",
      "A chance to win 1 full car share every time a vehicle is added to our collection",
      "DRVN Founder's Club phygital* hat",
      "DRVN PFP Airdrop – Uncommon (coming soon)",
    ],
  },
  carbon: {
    name: "Carbon Key Member",
    price: "$1,100 USDC",
    supply: "24 keys",
    color: "from-green-600 to-green-700",
    textColor: "text-green-300",
    icon: "Carbon.gif",
    benefits: [
      "All Steel level benefits, plus…",
      "0.25 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 1.25M $BSTR airdrop + Recurring $BSTR rewards",
      "VIP Presale access to every tokenized vehicle release",
      "DRVN Founder's Club phygital* jacket",
      "DRVN PFP Airdrop – Rare (coming soon)",
    ],
  },
  titanium: {
    name: "Titanium Key Member",
    price: "$4,000 USDC",
    supply: "7 keys",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-300",
    icon: "Titanium.gif",
    benefits: [
      "All Carbon level benefits, plus…",
      "1 full $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 4.75M $BSTR airdrop + Recurring $BSTR rewards",
      "Profit share on all revenue generated by the $RS1 Ferrari",
      "Exclusive $RS1 Ferrari phygital* merch",
      "Custom Key to the Ferrari",
      "Custom Titanium Club watch",
      "Titanium Club jacket",
      "DRVN PFP Airdrop – Legendary (coming soon)",
    ],
  },
};

export function BenefitsModal({
  isOpen,
  onClose,
  keyType,
}: BenefitsModalProps) {
  if (!isOpen) return null;

  const data = keyData[keyType];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal Content */}
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <Card className="bg-gradient-to-br from-gray-900 to-black border border-gray-700 backdrop-blur-sm">
          <CardContent className="p-0">
            {/* Header */}
            <div className="relative p-6 border-b border-gray-700">
              <button
                onClick={onClose}
                className="absolute top-4 right-4 p-2 hover:bg-gray-800 rounded-full transition-colors"
              >
                <X className="w-5 h-5 text-gray-400" />
              </button>

              <div className="flex items-center gap-4 mb-4">
                <div
                  className={`w-16 h-16 rounded-xl overflow-hidden bg-gradient-to-r ${data.color}`}
                >
                  <Image
                    src={`/Cars/${data.icon}`}
                    alt={`${data.name} Key`}
                    width={64}
                    height={64}
                    className="w-full h-full object-cover"
                    unoptimized
                  />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-white font-mono">
                    {data.name}
                  </h2>
                  <div className="flex items-center gap-4 mt-2">
                    <div className="flex items-center gap-1">
                      <DollarSign className="w-4 h-4 text-green-400" />
                      <span className="text-green-400 font-mono font-bold">
                        {data.price}
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Users className="w-4 h-4 text-blue-400" />
                      <span className="text-blue-400 font-mono">
                        {data.supply}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Benefits Section */}
            <div className="p-6">
              <div className="flex items-center gap-2 mb-6">
                <Gift className="w-6 h-6 text-yellow-500" />
                <h3 className="text-xl font-bold text-white font-mono">
                  Member Benefits
                </h3>
              </div>

              <div className="space-y-4">
                {data.benefits.map((benefit, index) => (
                  <div
                    key={index}
                    className="flex items-start gap-3 p-4 bg-gray-800/50 rounded-lg border border-gray-700"
                  >
                    <div className="flex-shrink-0 mt-1">
                      {index === 0 && keyType !== "steel" ? (
                        <Crown className="w-5 h-5 text-yellow-500" />
                      ) : (
                        <Star className="w-5 h-5 text-yellow-500" />
                      )}
                    </div>
                    <p className="text-gray-300 font-mono text-sm leading-relaxed">
                      {benefit}
                    </p>
                  </div>
                ))}
              </div>

              {/* Footer */}
              <div className="mt-8 pt-6 border-t border-gray-700">
                <div className="flex items-center justify-center gap-2 text-sm text-gray-400 font-mono">
                  <Zap className="w-4 h-4" />
                  <span>
                    Limited Supply • Exclusive Access • Premium Benefits
                  </span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
